spring.application.name=patitasya

spring.datasource.url=jdbc:postgresql://localhost:5432/patitasya
spring.datasource.username=postgres
spring.datasource.password=belgrano

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

cloudinary.cloud-name=dv6g2mzt0
cloudinary.api-key=799568337196759
cloudinary.api-secret=1zeHHNXgO41E1X9LhGmfvl3hC3c
